### ISSUE TITLE
Example for creation and regeneration of Overpass based challenge with a new query

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette-python-client#78]
**Is your feature request related to a problem? Please describe.**
I am planning to use API for what seems standard task - Overpass based challenge allowing to edit query, regenerated without going though a clunky web interface (using geojson based challenge as workaround for inability to change query in existing one - so overpass data would be downloaded locally)

Maybe also listing "too hard" and "already fixed" and other in some readable format before regeneration, maybe also skipping such entries from new iteration (would require local storage...)

**Describe the solution you'd like**
Examples folder has example of basic implementation (if noone published one so far - I can do this once I implement it)

**Describe alternatives you've considered**
Everyone implements it on their own.

**Additional context**
I checked examples folder and closest is https://github.com/osmlab/maproulette-python-client/blob/dev/examples/challenge_examples.py that creates challenge.

https://github.com/osmlab/maproulette-python-client/blob/dev/examples/project_examples.py  creates new project, what may be useful for initial run, to initialize a project

Code would have third-party dependence (likely on my library, though maybe I can find more established one) for downloading data from Overpass to avoid reinplementing the same a again.

**Comment by matkoniecz** [comment]
ping? I am not sure is it known to be infeasible, likely feasible but without working examples.

I am also unsure would it be a welcome contribution.

**Comment by mattmanley** [comment]
Sorry for the delay. I'd welcome any contribution you'd like to make. I'm not entirely sure what examples might satisfy your use-case, so feel free to poke around and see if you can come up with something.

**Comment by matkoniecz** [comment]
from looking at https://github.com/maproulette/maproulette3/issues/1563 - this approach is inherently blocked by some internal bad design so I will not pursue it. I prefer to avoid need to create new challenges to add new cases.
